links:
    - 🌸:
        - Github: https://github.com
        - Youtube: https://youtube.com
        - Tetra Channel: https://ch.tetr.io
      
    - Dev:
        - NodeJs Blog: https://nodejs.org/en/blog
      
    - Wiki:
        - HaskellWiki: https://wiki.haskell.org
        - ArchWiki: https://wiki.archlinux.org
    
    - deez:
        - nuts: https://4chan.org
      
    - Subreddit: 
        - r/indonesia: https://reddit.com/r/indonesia
        - r/tetris: https://reddit.com/r/tetris
        - r/unixporn: https://reddit.com/r/unixporn
        - r/okbuddyhetero: https://reddit.com/r/okbuddyhetero
